module.exports = {
  IndexData: {
    headerBackgroundImage: {uri:'../banner-top.jpg'},
    HotelNavBar: {
      dataSource: [
        {
          'text':['精选高星酒店', '3-7折起>'],
          'backgroundColor':'#ff7f00',
        },
        {
          'text':['经济酒店', '49元起>'],
          'backgroundColor':'f70f49',
        },
        {
          'text':['公寓也疯狂', '预付3折起>'],
          'backgroundColor':'#ff7f00',
        },
        {
          'text':['国际酒店', '低至5折>'],
          'backgroundColor':'f70f49',
        },
      ],
    },
    HotelListView: [
      {
        header: {
          backgroundImage:{uri:'../title-1.jpg'},
        },
        dataSource: [
          [
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
              'id':'90967360',
            },
            {
              'hotelname':'上海虹口三至喜来登酒店',
              'hotelimage':{uri:'../50201362.jpg'},
              'price':770,
              'star':'4星',
              'paytype':'预定',
              'id': '50201362',
            },
          ],
          [
            {
              'hotelname':'青岛丽天大酒店',
              'hotelimage':{uri:'../31601021.jpg'},
              'price':186,
              'star':'4星',
              'paytype':'预定',
              'id':'31601021',
            },
            {
              'hotelname':'广州凯港精品酒店(赤岗店)',
              'hotelimage':{uri:'../02001687.jpg'},
              'price':190,
              'star':'4星',
              'paytype':'预定',
              'id':'02001687',
            },
          ],
          [
            {
              'hotelname':'北京鸿炜亿家连锁酒店(金融街店)',
              'hotelimage':{uri:'../90693339.jpg'},
              'price':220,
              'star':'4星',
              'paytype':'预定',
              'id':'90693339',
            },
            {
              'hotelname':'深圳富临大酒店',
              'hotelimage':{uri:'../52003037.jpg'},
              'price':190,
              'star':'5星',
              'paytype':'预定',
              'id':'52003037',
            },
          ],
        ],
      },
      {
        header: {
          backgroundImage:{uri:'../title-2.jpg'},
        },
        dataSource: [
          [
            {
              'hotelname':'7天连锁酒店(北京密云鼓楼大街县政府店)',
              'hotelimage':{uri:'../00101612.jpg'},
              'price':97,
              'star':'3星',
              'paytype':'预定',
              'id':'00101612',
            },
            {
              'hotelname':'布丁酒店连锁(广州江泰路地铁站店)',
              'hotelimage':{uri:'../12001928.jpg'},
              'price':49,
              'star':'3星',
              'paytype':'预定',
              'id':'12001928',
            },
          ],
          [
            {
              'hotelname':'布丁酒店(火车站栈桥店)',
              'hotelimage':{uri:'../90912646.jpg'},
              'price':79,
              'star':'3星',
              'paytype':'预定',
              'id':'90912646',
            },
            {
              'hotelname':'汉庭海友酒店(上海锦江乐园店)(原华兴宾馆)',
              'hotelimage':{uri:'../60201786.jpg'},
              'price':51,
              'star':'3星',
              'paytype':'预定',
              'id':'60201786',
            },
          ],
          [
            {
              'hotelname':'尚客优快捷酒店(新机场航站楼店)',
              'hotelimage':{uri:'../90819032.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
              'id':'90819032',
            },
            {
              'hotelname':'汉庭酒店(武汉华师大店)',
              'hotelimage':{uri:'../01801270.jpg'},
              'price':80,
              'star':'3星',
              'paytype':'预定',
              'id':'01801270',
            },
          ],
        ],
      },
      {
        header: {
          backgroundImage:{uri:'../title-3.jpg'},
        },
        dataSource: [
          [
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
            },
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
            },
          ],
          [
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
            },
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
            },

          ],
        ],
      },
      {
        header: {
          backgroundImage:{uri:'../title-4.jpg'},
        },
        dataSource: [
          [
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
            },
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
            },
          ],
          [
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
            },
            {
              'hotelname':'成都上雅红叶酒店',
              'hotelimage':{uri:'../90967360.jpg'},
              'price':199,
              'star':'4星',
              'paytype':'预定',
            },
          ],
        ],
      },
    ],
  },
  DetailData: {
    headerhotellistImage: {uri:'../h5_jxgxjd_20151127.jpg'},
    citynumber:
    {
      number:"49",
    },
    citylist:[
      {
        cityname:"北京",
        cityid:"0",
      },
      {
        cityname:"重庆",
        cityid:"1",
      },
      {
        cityname:"成都",
        cityid:"2",
      },
      {
        cityname:"长沙",
        cityid:"3",
      },
    ],
    hotellist:[
      {
        cityname:"北京",
        cityid:"0",
        hoteldata:
        [
          {
            "hotelname":"北京上雅红叶酒店1",
            "hotelimage":"../90967360.jpg",
            "price":1,
            "discount":"房费4.5折",
            "area":"王府井",
          },
          {
            "hotelname":"北京上雅红叶酒店2",
            "hotelimage":"../90967360.jpg",
            "price":2,
            "discount":"房费3折",
            "area":"火星",
          },
          {
            "hotelname":"北京上雅红叶酒店3",
            "hotelimage":"../90967360.jpg",
            "price":3,
            "discount":"房费4.5折",
            "area":"王府井",
          },
          {
            "hotelname":"北京上雅红叶酒店4",
            "hotelimage":"../90967360.jpg",
            "price":4,
            "discount":"房费3折",
            "area":"火星",
          },
          {
            "hotelname":"北京上雅红叶酒店5",
            "hotelimage":"../31601021.jpg",
            "price":5,
            "discount":"房费3.5折",
            "area":"王府井",
          },
          {
            "hotelname":"北京上雅红叶酒店6",
            "hotelimage":"../31601021.jpg",
            "price":6,
            "discount":"房费4折",
            "area":"火星",
          },
        ],
      },
      {
        cityname:"重庆",
        cityid:"1",
        hoteldata:
        [
          {
            "hotelname":"重庆上雅红叶酒店1",
            "hotelimage":"../31601021.jpg",
            "price":567,
            "discount":"房费7折",
            "area":"月球",
          },
          {
            "hotelname":"重庆上雅红叶酒店2",
            "hotelimage":"../31601021.jpg",
            "price":890,
            "discount":"房费2折",
            "area":"非洲",
          },
          {
            "hotelname":"重庆上雅红叶酒店3",
            "hotelimage":"../31601021.jpg",
            "price":567,
            "discount":"房费7折",
            "area":"月球",
          },
          {
            "hotelname":"重庆上雅红叶酒店4",
            "hotelimage":"../31601021.jpg",
            "price":890,
            "discount":"房费2折",
            "area":"非洲",
          },
          {
            "hotelname":"重庆上雅红叶酒店5",
            "hotelimage":"../31601021.jpg",
            "price":567,
            "discount":"房费7折",
            "area":"月球",
          },
          {
            "hotelname":"重庆上雅红叶酒店6",
            "hotelimage":"../31601021.jpg",
            "price":890,
            "discount":"房费2折",
            "area":"非洲",
          },
        ],
      },
      {
        cityname:"成都",
        cityid:"2",
        hoteldata:
        [
          {
            "hotelname":"成都上雅红叶酒店1",
            "hotelimage":"../50201362.jpg",
            "price":399,
            "discount":"房费3折",
            "area":"月球",
          },
          {
            "hotelname":"成都上雅红叶酒店2",
            "hotelimage":"../50201362.jpg",
            "price":555,
            "discount":"房费5折",
            "area":"非洲",
          },
          {
            "hotelname":"成都上雅红叶酒店3",
            "hotelimage":"../50201362.jpg",
            "price":399,
            "discount":"房费3折",
            "area":"月球",
          },
          {
            "hotelname":"成都上雅红叶酒店4",
            "hotelimage":"../50201362.jpg",
            "price":555,
            "discount":"房费5折",
            "area":"非洲",
          },
          {
            "hotelname":"成都上雅红叶酒店5",
            "hotelimage":"../50201362.jpg",
            "price":399,
            "discount":"房费3折",
            "area":"月球",
          },
          {
            "hotelname":"成都上雅红叶酒店6",
            "hotelimage":"../50201362.jpg",
            "price":555,
            "discount":"房费5折",
            "area":"非洲",
          },
        ],
      },
      {
        cityname:"长沙",
        cityid:"3",
        hoteldata:
        [
          {
            "hotelname":"长沙上雅红叶酒店1",
            "hotelimage":"../50201362.jpg",
            "price":399,
            "discount":"房费3折",
            "area":"月球",
          },
          {
            "hotelname":"长沙上雅红叶酒店2",
            "hotelimage":"../50201362.jpg",
            "price":555,
            "discount":"房费5折",
            "area":"非洲",
          },
          {
            "hotelname":"长沙上雅红叶酒店3",
            "hotelimage":"../50201362.jpg",
            "price":399,
            "discount":"房费3折",
            "area":"月球",
          },
          {
            "hotelname":"长沙上雅红叶酒店4",
            "hotelimage":"../50201362.jpg",
            "price":555,
            "discount":"房费5折",
            "area":"非洲",
          },
          {
            "hotelname":"长沙上雅红叶酒店5",
            "hotelimage":"../50201362.jpg",
            "price":399,
            "discount":"房费3折",
            "area":"月球",
          },
          {
            "hotelname":"长沙上雅红叶酒店6",
            "hotelimage":"../50201362.jpg",
            "price":555,
            "discount":"房费5折",
            "area":"非洲",
          },
        ],
      },
    ],
  },
  CityData:{
    data: {
      A: ['澳门'],
      B: ['北京'],
      C: ['成都','重庆','长沙'],
      D: ['东兴市','大同市','大丰市'],
      E: ['二连浩特市','恩施土家族苗族自治州','鄂州市'],
      F: ['丰宁坝上','福安市','方城县','府谷县','奉化市'],
      G: ['广州','高邑县','广水市','广安市','广元市'],
      H: ['杭州','含山县','霍州市','海门市','霍山县'],
      J: ['济南','建水县','九台市','井冈山市','吉林市'],
      N: ['南京','福安市','方城县','府谷县','奉化市'],
      Q: ['青岛','福安市','方城县','府谷县','奉化市'],
      S: ['上海','深圳','苏州'],
      T: ['天津'],
      V: ['武汉'],
      X: ['厦门','西安'],
    },
  },
};
